apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany  # để các pod cùng đọc/ghi
  hostPath:
    path: /mnt/data/uploads  # thư mục trên máy chủ
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Mi
